language: python

python:
    - "2.7"

install:
    # install mozbattue code and test dependencies
    - pip install mock flake8
    - pip install -e .

before_script:
    - flake8 mozbattue tests setup.py

script:
    - python setup.py test
